name: Bump version on develop merge

on:
  push:
    branches:
      - develop

permissions:
  contents: write  # Needed to allow pushing changes back

jobs:
  bump-version:
    runs-on: self-hosted

    steps:
      - name: Bump version
        run: |
          echo "Test"
