name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Prepare minimal publish folder
        run: |
          mkdir temp
          cp dist/index.cjs temp/index.cjs
          cp src/index.d.ts temp/index.d.ts
          VERSION=$(node -p "require('./package.json').version")
          echo "{
            \"name\": \"noblex\",
            \"version\": \"$VERSION\",
            \"main\": \"index.cjs\",
            \"types\": \"index.d.ts\",
            \"files\": [\"index.cjs\", \"index.d.ts\"],
            \"license\": \"MIT\",
            \"dependencies\": {}
          }" > temp/package.json

      - name: Publish to NPM
        run: npm publish ./temp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
